### PR TITLE
Sticky and pm historcal cellular yields modifications

### PR DESCRIPTION
**Pull request by emolinab**

### CODE REVIEW

**Review by flohump — COMMENTED** [review]
I think the initialization of vm_prod should happen in 17_production, the module providing this interface. @tscheypidi What do you think?

**Comment by flohump** [comment]
Why does the unit change from MER to PPP? Is this change limited to the sticky realization? What about the other realizations?

**Comment by emolinab** [comment]
For the vm_prod initialization, we saw that it has a different importance for free and dynamic. That's why there is a switch to turn it ON or OFF based on how you are running sticky. Regarding MER and PPP, this was only changed in sticky since for this realization we calculate the factor requirements based on FAO VoP data and USDA factor shares. For the other realizations, the requirements come from GTAP data.

**Comment by weindl** [comment]
> 
> 
> I think the initialization of vm_prod should happen in 17_production, the module providing this interface. @tscheypidi What do you think?

I think the factor costs module is choosen  for the initialization, since the decision if the initialization takes place or not depends on the settings in the factor costs module.

**Comment by weindl** [comment]
Looks good.

**Comment by tscheypidi** [comment]
> For the vm_prod initialization, we saw that it has a different importance for free and dynamic. That's why there is a switch to turn it ON or OFF based on how you are running sticky. Regarding MER and PPP, this was only changed in sticky since for this realization we calculate the factor requirements based on FAO VoP data and USDA factor shares. For the other realizations, the requirements come from GTAP data.

I agree with Florian, that setting the levels of a variable should happen in the module which declares the variable. In addition, I don't think that the choice of a realization should affect the decision whether levels are set or not. I can see that setting the levels might be beneficial to improve the optimization process, but I do not see a reason why it should be necessary to not initialize a variable. I suggest to either completely avoid setting the levels or setting them in the production module for all runs

Concerning the unit change: Are you saying that the unit of the corresponding variables/parameters change depending on which realization is switched on? If so, then this also has to be changed as the unit of an object must be directly attached to the name of the object so that identical names indicate also identical units. Otherwise we will continously running into the issue to misinterpret the values of a variable/parameter

**Comment by emolinab** [comment]
Regarding the units, this is actually a correction to that, now all the realization report MER.

**Comment by flohump** [comment]
Looks good. pm_yields_hist should be removed from the not_used files in 38_factor_costs

**Pull request merged**
